name: Ning-trigger-workflow

on:
  push:
    branches: [ main, develop, "*" ]
    paths:
      - 'src/**'
      - 'package.json'
      - '**.js'
      - '**'
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
    
env:
  DEFAULT_BRANCH: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  trigger-tests:
    name: Trigger Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code 3
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Event Action: ${{ github.event.action }}"
        echo "Ref: ${{ github.workflow }}"
        echo "Ref: ${{ github.head_ref }}"
        echo "Ref: ${{ github.ref_name }}"
        echo "Ref: $DEFAULT_BRANCH"



