name: Ning-trigger-workflow

on:
  push:
    branches: [ main, develop, "*" ]
    paths:
      - 'src/**'
      - 'package.json'
      - '**.js'
      - '**'
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
    
env:
  NON_DEFAULT_BRANCH: ${{ github.ref != 'refs/heads/main' && format('{0}-{1}', github.workflow, github.ref_name) || format('{0}-{1}', github.workflow, github.run_id) }}

concurrency:
  group: ${{ (github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master') && format('{0}-{1}', github.workflow, github.ref_name) || format('{0}-{1}', github.workflow, github.run_id) }}
  cancel-in-progress: true

jobs:
  trigger-tests:
    name: Trigger Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code 3
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Event Action: ${{ github.event.action }}"
        echo "workflow: ${{ github.workflow }}"
        echo "head_ref: ${{ github.head_ref }}"
        echo "ref_name: ${{ github.ref_name }}"
        echo "ref: ${{ github.ref }}"
        echo "NON_DEFAULT_BRANCH: $NON_DEFAULT_BRANCH"



