name: Ning trigger test workflow

on:
  push:
    branches: [ main, develop, feature/* ]
    paths:
      - 'src/**'
      - 'package.json'
      - '**.js'
      - '**'
  pull_request:
    # branches: [ main, develop ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-tests:
    if: github.event_name == 'pull_request' || ( github.event_name == 'push' && github.event.pull_request == null )
    name: Trigger Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Event Action: ${{ github.event.action }}"
        echo "Ref: ${{ github.ref }}"
        echo "workflow: ${{ github.event.pull_request }}"
        echo "workflow: ${{ github.event.pull_request == null }}"
        echo "workflow: ${{ github.event.head_commit.message }}"
        sleep 180

